name: Create Pull Request
on:
  push:
    branches:
      - dev
jobs:
  create-pull-request:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: main