name: Create Pull Request
on:
  push:
    branches:
      - dev
permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull-request
        run: |
          gh pr create --base main --title "my pull request" --body "description"1