name: Create Pull Request
on:
  push:
    branches:
      - dev
permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if PR exists
        run: |
          gh pr create -B develop --title "Merge ${{ github.ref_name }} into develop" --body 'Created by Github action' || gh pr edit -B develop --title "Merge ${{ github.ref_name }} into develop" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ github.token }}