name: Create Pull Request
on:
  push:
    branches:
      - dev
permissions:
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh pr create --base main --title "Dev to main"