name: Create Pull Request
on:
  push:
    branches:
      - dev
permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create PR to merge dev into main
        run: |
          gh pr create -B main --title "Merge dev into main" --body 'Created by Github action' || gh pr edit -B main --title "dev into main" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ github.token }}