name: Create Pull Request
on:
  push:
    branches:
      - main
jobs:
  create-pull-request:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: dev